### ISSUE TITLE
Rendering functions doesn't handle page assets injected

### ISSUE THREAD

**Issue by damsfx** [wintercms/wn-blocks-plugin#15]
When using `renderBlocks()` or `renderBlock()`, if the block php section contains a page assets injection, it won't work.  

```twig
name: 'MyBlock'
...
fields:
    ...
==
<?php
    function onStart()
    {
        $this->controller->addCss(Url::asset('/plugins/acme/myplugin/assets/css/blocks.css'));
    }
?>
==
<div class="block">
    ...
</div>
```

Workaround :  
use `{% partial 'blocks' blocks=blocks %}`

**Comment by LukeTowers** [comment]
@jaxwilko any ideas?

**Comment by jaxwilko** [comment]
@LukeTowers pretty sure it's because they call `(new Controller())->renderPartial(...);` which means they get rendered against `new Controller()` and not the page controller, which means the php section's `$this` refers to the wrong controller and the assets are lost after the partial has been rendered.

How are the 2 render functions to be used? We could fake a page render instead and include `{% scripts %}` & `{% styles %}` around the rendered block(s) code

**Comment by LukeTowers** [comment]
The render functions should probably accept an optional controller instance and then the twig function should ideally pass the controller context on to the render functions.

**Comment by damsfx** [comment]
@LukeTowers Did you get this to work?
All my attempts are unsuccessful, the css is never loaded.

**Comment by damsfx** [comment]
@LukeTowers I have 77a10aacd68cd045208562877d84052be8e8879e commit localy.

I found out why it only works for scripts, but not for styles. 

For this to work, I need to have the `{% styles %}` placeholder at the end of my layout (after rendering the blocks), which isn't a valid option for me as my styles need to be loaded into the <head /> of the document for best rendering.

Workaround : Render the blocks in a variable before my layout.

```twig
description = "Default layout"
==
{% set blocksContent %} 
{% if blocks %}
    {% partial 'blocks' blocks=blocks %}
{% endif %}
{% endset %}

{% set layoutOutput %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% styles %}
</head>
<body>
    {{ blocksContent }}
</body>
</html>
{% endset %}

{% if this.environment == 'dev' %}
{{ layoutOutput }}
{% else %}
{% apply spaceless %}
{{ layoutOutput }}
{% endapply %}
{% endif %}
```

ps: I render my compiled layout in a `layoutOutput` variable to avoid "spaghetti code" in production.

**Comment by jaxwilko** [comment]
@LukeTowers i don't think it'll work, the events just aren't fired in order for that. Generally I use mix/vite to compile all my theme css including block and that allows me to have better control of the loading impact of that css file that it would by having multiple smaller files.

Js is a different question, but assuming you're calling `{% scripts %}` at the end of the page it should work

**Comment by damsfx** [comment]
> ... Generally I use mix/vite to compile all my theme css including blocks and that allows me to have better control of the loading impact of that css file than it would by having multiple smaller files.
> 

@jaxwilko I use the same process, but in this case, the **CSS is provided by a third plugin**, offering blocks for the Winter.Blocks plugin.
This is a bit of a special case, but as third-party plugins can provide scripts to enhance their blocks, they could also offer styles to improve the visual appearance of rendered blocks.
