### ISSUE TITLE
Improve hierarchical context

### ISSUE THREAD

**Issue by bennothommo** [wintercms/wn-blocks-plugin#16]
I have a scenario where I am creating top-level container blocks, for example, single or double columns, that have a specific theme - let's say either a light, dark, or white theme. As far as I can tell, there's no way for me to populate this "theme" to all blocks, child blocks, grandchild blocks, etc. so I can use differing colours for textual content, buttons, etc.

Ideally, this could be some sort of variable "bag" which can be set at the top most level, and either remain the same or change as it goes down the heirarchy. Each child could potentially add new variables to this bag as it passes down too.

**Comment by LukeTowers** [comment]
Could you submit your idea as a PR?

**Comment by bennothommo** [comment]
Not going to go ahead with this, at this stage.
