### ISSUE TITLE
Columns for `columns_two` can't get empty

### ISSUE THREAD

**Issue by damsfx** [wintercms/wn-blocks-plugin#20]
I'm not really sure if this is a bug, because the columns aren't supposed to be empty, but if a `columns_two` block is added without any content (or one of the columns doesn't have any), then an error is thrown: 
```
Winter\Blocks\Plugin::Winter\Blocks\{closure}(): Argument #2 ($blocks) must be of type array, null given, ... 
```

Maybe a fallback to an empty array is needed in this case.

**Comment by LukeTowers** [comment]
@damsfx I'd agree with you, can you submit a PR?
