### ISSUE TITLE
[Bug] Initial block 'add item' FormWidget only appears in the Meta section of Static Pages

### ISSUE THREAD

**Issue by nmiyazaki-chapleau** [wintercms/wn-blocks-plugin#32]
When no blocks have been defined yet, the "add item" field only exists in the "meta" section of a Static Page.

![image](https://github.com/wintercms/wn-blocks-plugin/assets/104367522/7f2b5d81-fe61-4182-81c4-2f0817d352fd)
![image](https://github.com/wintercms/wn-blocks-plugin/assets/104367522/3c243eec-1d36-4d7c-a105-275db687875c)

We can also see the Markup section is only disabled on the "meta" section.
Once any block is added, the blocks appear in the main section as well.

The static page layout:
```
description = "Default layout for static"

[staticPage]
useContent = 1
default = 0

[localePicker]
forceUrl = 0
==
{% partial "site/header" %}

{% component 'staticPage' %}
{{ renderBlocks(blocks ?? []) }}

{% partial "site/footer" %}
{variable type="blocks" name="blocks" tab="winter.pages::lang.editor.content"}{/variable}
```

**Comment by damsfx** [comment]
Not sure the page can handle default content and blocks in the same time.

Try :
```twig
[staticPage]
useContent = 0
default = 0
```
To see if the behavior change.
