### ISSUE TITLE
[Bug] Blocks don't appear in Static Pages if screen resolution is too high

### ISSUE THREAD

**Issue by nmiyazaki-chapleau** [wintercms/wn-blocks-plugin#33]
The blocks section of a Static Page disappears if the screen resolution is too high. I am unsure of the dimensions, but on a 1920x1080 screen, zooming out to 110% does the trick.
This is affecting a colleague that has a monitor with a 2K resolution.

**Comment by damsfx** [comment]
In this case, providing screenshots can help!

**Comment by LukeTowers** [comment]
This is probably because the content field is set to stretch to the full height which probably doesn't play nice with having fields after it. You could always add it to a different tab if you wanted to have both the richeditor and the blocks field.
